# кол-во конкуретных сессий пользователей, необязательный параметр, по умолчанию 1
concurrency: 1000

# кол-во повторений сценария, необязательный параметр, по умолчанию 1
loopCount: 10

# время ожидания ответа от сервера, необязательный параметр, по умолчанию 2 секунды
timeout: 5

# сетевой протокол http или https, необязательный параметр, по умолчанию http
scheme: https

# доменное имя хоста или IP-адрес, обязательный параметр
host: example.com

# порт хоста для подключения
port: 8080

# глобальные заголовки, которые будут вставлены в каждый запрос сценария, необязательный параметр
headers:
  Content-Type: text/html; charset=utf-8
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36 FirePHP/4Chrome

# последовательность запросов, которые необходимо выполнить, необязательный параметр, если запросы не указаны, то программа выполнит один GET запрос на /
requests:

  # GET|POST|PUT|DELETE: /path?query
  - GET: /index

  - POST: /signin?key=value
    # необязательные POST параметры
    params:
      login: user
      password: passw0rd
    # время ожидания ответа от сервера этого запроса, необязательный параметр, по умолчанию будет использован глобальный таймаут
    timeout: 10

  - GET: /profile
    # заголовки этого запроса, необязательный параметр
    headers:
      X-Key-1: Value-1
      X-Key-2: Value-2


